Fix errors in Linux compilation
cameron314/concurrentqueue pull request #295
Opened 2022-05-09 08:58 UTC by Tiline

2022-05-09 11:41 UTC, cameron314 requested changes
What is the actual issue you're trying to solve? As far as I can tell the original code is correct.

2022-05-09 11:41 UTC, cameron314 commented on c_api/concurrentqueue.h
> +    #define MOODYCAMEL_EXPORT
Doesn't make sense to redefine if already defined.

2022-05-09 11:41 UTC, cameron314 commented on c_api/concurrentqueue.h
> +    #elif __APPLE__
What about platforms besides Windows, Linux, and Apple?

2022-05-09 11:41 UTC, cameron314 commented on c_api/concurrentqueue.h
> -MOODYCAMEL_EXPORT size_t moodycamel_cq_size_approx(MoodycamelCQHandle handle);
Still need this! (And the include for size_t too)

2022-05-09 12:00 UTC, Tiline commented
Sorry, I encountered the following error when trying to compile the project under Linux:
```
[build]# make
In file included from ../c_api/blockingconcurrentqueue.cpp:1:0:
../c_api/concurrentqueue.h:25:1: error: ‘MOODYCAMEL_EXPORT’ does not name a type
 MOODYCAMEL_EXPORT int moodycamel_cq_create(MoodycamelCQHandle* handle);
 ...
```
When I view that macros are undefined, they can only be defined under windows

I'm not sure if I need to judge other platforms???

2022-05-09 12:00 UTC, Tiline commented
Sorry, I encountered the following error when trying to compile the project under Linux:
```
[build]# make
In file included from ../c_api/blockingconcurrentqueue.cpp:1:0:
../c_api/concurrentqueue.h:25:1: error: ‘MOODYCAMEL_EXPORT’ does not name a type
 MOODYCAMEL_EXPORT int moodycamel_cq_create(MoodycamelCQHandle* handle);
 ...
```
When I view that macros are undefined, they can only be defined under Windows

I'm not sure if I need to judge other platforms???

2022-05-09 13:19 UTC, cameron314 commented
> When I view that macros are undefined, they can only be defined under Windows

Where do you see this? In the original code, the `#ifdef _WIN32` is matched with an `#else #define MOODYCAMEL_EXPORT`.

Judging from the line number in your error message, it seems likely you're using an older version of the library which had this bug (fixed about a year ago: https://github.com/cameron314/concurrentqueue/commit/e6fec438e8639221d43dae4b2ddf133e20580fdd).

2022-05-10 00:59 UTC, Tiline commented
对不起，我确认了下代码是在v1.0.3下，在master分支下编译正确

2022-05-10 00:59 UTC, closed without merging